/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DecodeYourMindRouteImport } from './routes/decode-your-mind'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardResultsRouteImport } from './routes/dashboard/results'
import { Route as DashboardEbooksRouteImport } from './routes/dashboard/ebooks'
import { Route as AssessmentsSlugRouteImport } from './routes/assessments/$slug'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DecodeYourMindRoute = DecodeYourMindRouteImport.update({
  id: '/decode-your-mind',
  path: '/decode-your-mind',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResultsRoute = DashboardResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEbooksRoute = DashboardEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AssessmentsSlugRoute = AssessmentsSlugRouteImport.update({
  id: '/assessments/$slug',
  path: '/assessments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/contact': typeof ContactRoute
  '/decode-your-mind': typeof DecodeYourMindRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/assessments/$slug': typeof AssessmentsSlugRoute
  '/dashboard/ebooks': typeof DashboardEbooksRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/contact': typeof ContactRoute
  '/decode-your-mind': typeof DecodeYourMindRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/assessments/$slug': typeof AssessmentsSlugRoute
  '/dashboard/ebooks': typeof DashboardEbooksRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/contact': typeof ContactRoute
  '/decode-your-mind': typeof DecodeYourMindRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/assessments/$slug': typeof AssessmentsSlugRoute
  '/dashboard/ebooks': typeof DashboardEbooksRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/academy'
    | '/contact'
    | '/decode-your-mind'
    | '/privacy-policy'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/assessments/$slug'
    | '/dashboard/ebooks'
    | '/dashboard/results'
    | '/dashboard/settings'
    | '/assessments/'
    | '/dashboard/'
    | '/api/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/contact'
    | '/decode-your-mind'
    | '/privacy-policy'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/assessments/$slug'
    | '/dashboard/ebooks'
    | '/dashboard/results'
    | '/dashboard/settings'
    | '/assessments'
    | '/dashboard'
    | '/api/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/academy'
    | '/contact'
    | '/decode-your-mind'
    | '/privacy-policy'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/assessments/$slug'
    | '/dashboard/ebooks'
    | '/dashboard/results'
    | '/dashboard/settings'
    | '/assessments/'
    | '/dashboard/'
    | '/api/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  ContactRoute: typeof ContactRoute
  DecodeYourMindRoute: typeof DecodeYourMindRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AssessmentsSlugRoute: typeof AssessmentsSlugRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decode-your-mind': {
      id: '/decode-your-mind'
      path: '/decode-your-mind'
      fullPath: '/decode-your-mind'
      preLoaderRoute: typeof DecodeYourMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/results': {
      id: '/dashboard/results'
      path: '/results'
      fullPath: '/dashboard/results'
      preLoaderRoute: typeof DashboardResultsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ebooks': {
      id: '/dashboard/ebooks'
      path: '/ebooks'
      fullPath: '/dashboard/ebooks'
      preLoaderRoute: typeof DashboardEbooksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/assessments/$slug': {
      id: '/assessments/$slug'
      path: '/assessments/$slug'
      fullPath: '/assessments/$slug'
      preLoaderRoute: typeof AssessmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardEbooksRoute: typeof DashboardEbooksRoute
  DashboardResultsRoute: typeof DashboardResultsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardEbooksRoute: DashboardEbooksRoute,
  DashboardResultsRoute: DashboardResultsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  ContactRoute: ContactRoute,
  DecodeYourMindRoute: DecodeYourMindRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AssessmentsSlugRoute: AssessmentsSlugRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
