/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForOrganizationsRouteImport } from './routes/for-organizations'
import { Route as ForIndividualsRouteImport } from './routes/for-individuals'
import { Route as DecodeYourMindRouteImport } from './routes/decode-your-mind'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OrgRouteRouteImport } from './routes/org/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as OrgCreditsRouteImport } from './routes/org/credits'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardResultsRouteImport } from './routes/dashboard/results'
import { Route as DashboardEbooksRouteImport } from './routes/dashboard/ebooks'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as AuthedResourcesRouteImport } from './routes/_authed/resources'
import { Route as AuthedAcademyRouteImport } from './routes/_authed/academy'
import { Route as OrgCampaignsIndexRouteImport } from './routes/org/campaigns/index'
import { Route as AuthedAssessmentsIndexRouteImport } from './routes/_authed/assessments/index'
import { Route as OrgCampaignsNewRouteImport } from './routes/org/campaigns/new'
import { Route as OrgCampaignsCampaignIdRouteImport } from './routes/org/campaigns/$campaignId'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'
import { Route as AuthedAssessmentsSlugRouteImport } from './routes/_authed/assessments/$slug'
import { Route as ApiEbooksEbookIdPdfRouteImport } from './routes/api/ebooks/$ebookId/pdf'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOrganizationsRoute = ForOrganizationsRouteImport.update({
  id: '/for-organizations',
  path: '/for-organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForIndividualsRoute = ForIndividualsRouteImport.update({
  id: '/for-individuals',
  path: '/for-individuals',
  getParentRoute: () => rootRouteImport,
} as any)
const DecodeYourMindRoute = DecodeYourMindRouteImport.update({
  id: '/decode-your-mind',
  path: '/decode-your-mind',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRouteRoute = OrgRouteRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgCreditsRoute = OrgCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => OrgRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResultsRoute = DashboardResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEbooksRoute = DashboardEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedResourcesRoute = AuthedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAcademyRoute = AuthedAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const OrgCampaignsIndexRoute = OrgCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const AuthedAssessmentsIndexRoute = AuthedAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const OrgCampaignsNewRoute = OrgCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgCampaignsCampaignIdRoute = OrgCampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => OrgRouteRoute,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAssessmentsSlugRoute = AuthedAssessmentsSlugRouteImport.update({
  id: '/assessments/$slug',
  path: '/assessments/$slug',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiEbooksEbookIdPdfRoute = ApiEbooksEbookIdPdfRouteImport.update({
  id: '/api/ebooks/$ebookId/pdf',
  path: '/api/ebooks/$ebookId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/decode-your-mind': typeof DecodeYourMindRoute
  '/for-individuals': typeof ForIndividualsRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/academy': typeof AuthedAcademyRoute
  '/resources': typeof AuthedResourcesRoute
  '/a/$token': typeof ATokenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/ebooks': typeof DashboardEbooksRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/org/credits': typeof OrgCreditsRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/org/': typeof OrgIndexRoute
  '/assessments/$slug': typeof AuthedAssessmentsSlugRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/org/campaigns/$campaignId': typeof OrgCampaignsCampaignIdRoute
  '/org/campaigns/new': typeof OrgCampaignsNewRoute
  '/assessments/': typeof AuthedAssessmentsIndexRoute
  '/org/campaigns/': typeof OrgCampaignsIndexRoute
  '/api/ebooks/$ebookId/pdf': typeof ApiEbooksEbookIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/decode-your-mind': typeof DecodeYourMindRoute
  '/for-individuals': typeof ForIndividualsRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/academy': typeof AuthedAcademyRoute
  '/resources': typeof AuthedResourcesRoute
  '/a/$token': typeof ATokenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/ebooks': typeof DashboardEbooksRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/org/credits': typeof OrgCreditsRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/org': typeof OrgIndexRoute
  '/assessments/$slug': typeof AuthedAssessmentsSlugRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/org/campaigns/$campaignId': typeof OrgCampaignsCampaignIdRoute
  '/org/campaigns/new': typeof OrgCampaignsNewRoute
  '/assessments': typeof AuthedAssessmentsIndexRoute
  '/org/campaigns': typeof OrgCampaignsIndexRoute
  '/api/ebooks/$ebookId/pdf': typeof ApiEbooksEbookIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/decode-your-mind': typeof DecodeYourMindRoute
  '/for-individuals': typeof ForIndividualsRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authed/academy': typeof AuthedAcademyRoute
  '/_authed/resources': typeof AuthedResourcesRoute
  '/a/$token': typeof ATokenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/ebooks': typeof DashboardEbooksRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/org/credits': typeof OrgCreditsRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/org/': typeof OrgIndexRoute
  '/_authed/assessments/$slug': typeof AuthedAssessmentsSlugRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/org/campaigns/$campaignId': typeof OrgCampaignsCampaignIdRoute
  '/org/campaigns/new': typeof OrgCampaignsNewRoute
  '/_authed/assessments/': typeof AuthedAssessmentsIndexRoute
  '/org/campaigns/': typeof OrgCampaignsIndexRoute
  '/api/ebooks/$ebookId/pdf': typeof ApiEbooksEbookIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/org'
    | '/about'
    | '/contact'
    | '/decode-your-mind'
    | '/for-individuals'
    | '/for-organizations'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/academy'
    | '/resources'
    | '/a/$token'
    | '/blog/$slug'
    | '/dashboard/ebooks'
    | '/dashboard/results'
    | '/dashboard/settings'
    | '/org/credits'
    | '/blog/'
    | '/dashboard/'
    | '/org/'
    | '/assessments/$slug'
    | '/api/webhooks/razorpay'
    | '/org/campaigns/$campaignId'
    | '/org/campaigns/new'
    | '/assessments/'
    | '/org/campaigns/'
    | '/api/ebooks/$ebookId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/decode-your-mind'
    | '/for-individuals'
    | '/for-organizations'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/academy'
    | '/resources'
    | '/a/$token'
    | '/blog/$slug'
    | '/dashboard/ebooks'
    | '/dashboard/results'
    | '/dashboard/settings'
    | '/org/credits'
    | '/blog'
    | '/dashboard'
    | '/org'
    | '/assessments/$slug'
    | '/api/webhooks/razorpay'
    | '/org/campaigns/$campaignId'
    | '/org/campaigns/new'
    | '/assessments'
    | '/org/campaigns'
    | '/api/ebooks/$ebookId/pdf'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/dashboard'
    | '/org'
    | '/about'
    | '/contact'
    | '/decode-your-mind'
    | '/for-individuals'
    | '/for-organizations'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authed/academy'
    | '/_authed/resources'
    | '/a/$token'
    | '/blog/$slug'
    | '/dashboard/ebooks'
    | '/dashboard/results'
    | '/dashboard/settings'
    | '/org/credits'
    | '/blog/'
    | '/dashboard/'
    | '/org/'
    | '/_authed/assessments/$slug'
    | '/api/webhooks/razorpay'
    | '/org/campaigns/$campaignId'
    | '/org/campaigns/new'
    | '/_authed/assessments/'
    | '/org/campaigns/'
    | '/api/ebooks/$ebookId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OrgRouteRoute: typeof OrgRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DecodeYourMindRoute: typeof DecodeYourMindRoute
  ForIndividualsRoute: typeof ForIndividualsRoute
  ForOrganizationsRoute: typeof ForOrganizationsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ATokenRoute: typeof ATokenRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
  ApiEbooksEbookIdPdfRoute: typeof ApiEbooksEbookIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-organizations': {
      id: '/for-organizations'
      path: '/for-organizations'
      fullPath: '/for-organizations'
      preLoaderRoute: typeof ForOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-individuals': {
      id: '/for-individuals'
      path: '/for-individuals'
      fullPath: '/for-individuals'
      preLoaderRoute: typeof ForIndividualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decode-your-mind': {
      id: '/decode-your-mind'
      path: '/decode-your-mind'
      fullPath: '/decode-your-mind'
      preLoaderRoute: typeof DecodeYourMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/credits': {
      id: '/org/credits'
      path: '/credits'
      fullPath: '/org/credits'
      preLoaderRoute: typeof OrgCreditsRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/results': {
      id: '/dashboard/results'
      path: '/results'
      fullPath: '/dashboard/results'
      preLoaderRoute: typeof DashboardResultsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ebooks': {
      id: '/dashboard/ebooks'
      path: '/ebooks'
      fullPath: '/dashboard/ebooks'
      preLoaderRoute: typeof DashboardEbooksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/resources': {
      id: '/_authed/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthedResourcesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/academy': {
      id: '/_authed/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AuthedAcademyRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/org/campaigns/': {
      id: '/org/campaigns/'
      path: '/campaigns'
      fullPath: '/org/campaigns/'
      preLoaderRoute: typeof OrgCampaignsIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_authed/assessments/': {
      id: '/_authed/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthedAssessmentsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/org/campaigns/new': {
      id: '/org/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/org/campaigns/new'
      preLoaderRoute: typeof OrgCampaignsNewRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/campaigns/$campaignId': {
      id: '/org/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/org/campaigns/$campaignId'
      preLoaderRoute: typeof OrgCampaignsCampaignIdRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/assessments/$slug': {
      id: '/_authed/assessments/$slug'
      path: '/assessments/$slug'
      fullPath: '/assessments/$slug'
      preLoaderRoute: typeof AuthedAssessmentsSlugRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/ebooks/$ebookId/pdf': {
      id: '/api/ebooks/$ebookId/pdf'
      path: '/api/ebooks/$ebookId/pdf'
      fullPath: '/api/ebooks/$ebookId/pdf'
      preLoaderRoute: typeof ApiEbooksEbookIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAcademyRoute: typeof AuthedAcademyRoute
  AuthedResourcesRoute: typeof AuthedResourcesRoute
  AuthedAssessmentsSlugRoute: typeof AuthedAssessmentsSlugRoute
  AuthedAssessmentsIndexRoute: typeof AuthedAssessmentsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAcademyRoute: AuthedAcademyRoute,
  AuthedResourcesRoute: AuthedResourcesRoute,
  AuthedAssessmentsSlugRoute: AuthedAssessmentsSlugRoute,
  AuthedAssessmentsIndexRoute: AuthedAssessmentsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardEbooksRoute: typeof DashboardEbooksRoute
  DashboardResultsRoute: typeof DashboardResultsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardEbooksRoute: DashboardEbooksRoute,
  DashboardResultsRoute: DashboardResultsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OrgRouteRouteChildren {
  OrgCreditsRoute: typeof OrgCreditsRoute
  OrgIndexRoute: typeof OrgIndexRoute
  OrgCampaignsCampaignIdRoute: typeof OrgCampaignsCampaignIdRoute
  OrgCampaignsNewRoute: typeof OrgCampaignsNewRoute
  OrgCampaignsIndexRoute: typeof OrgCampaignsIndexRoute
}

const OrgRouteRouteChildren: OrgRouteRouteChildren = {
  OrgCreditsRoute: OrgCreditsRoute,
  OrgIndexRoute: OrgIndexRoute,
  OrgCampaignsCampaignIdRoute: OrgCampaignsCampaignIdRoute,
  OrgCampaignsNewRoute: OrgCampaignsNewRoute,
  OrgCampaignsIndexRoute: OrgCampaignsIndexRoute,
}

const OrgRouteRouteWithChildren = OrgRouteRoute._addFileChildren(
  OrgRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OrgRouteRoute: OrgRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DecodeYourMindRoute: DecodeYourMindRoute,
  ForIndividualsRoute: ForIndividualsRoute,
  ForOrganizationsRoute: ForOrganizationsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ATokenRoute: ATokenRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
  ApiEbooksEbookIdPdfRoute: ApiEbooksEbookIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
